version: 2

updates:
    # NPM: 1x weekly for minor/patch, 1x monthly for major.
    - package-ecosystem: 'npm'
      directories:
          - '/'
          - 'examples/*'
          - 'packages/*'
      schedule:
          interval: 'weekly'
      cooldown:
          semver-major-days: 30
          semver-minor-days: 7
          semver-patch-days: 7
      groups:
          npm-dev-minor-patch:
              dependency-type: 'development'
              update-types: [minor, patch]
          npm-prod-minor-patch:
              dependency-type: 'production'
              update-types: [minor, patch]

    # GitHub Actions: 1x weekly.
    - package-ecosystem: 'github-actions'
      directory: '/'
      schedule:
          interval: 'weekly'
      groups:
          github-actions-updates:
              patterns: ['*']
