name: Bug report
description: Create a bug report for SnapWP
body:
    - type: markdown
      attributes:
          value: >-
              Thank you for taking the time to report a possible bug!

              Please remember, a bug report is not the place to ask questions. You can
              use Discord for that, or start a topic in [GitHub
              Discussions](https://github.com/rtCamp/snapwp/discussions).

    - type: textarea
      attributes:
          label: Description
          description: >-
              Please write a brief description of the bug, including what you expected
              and what actually happened.
      validations:
          required: true

    - type: input
      attributes:
          label: Link to the code that reproduces this issue
          description: |
              A link to a **public**[GitHub repository or a CodeSandbox minimal reproduction. 

              **Skipping this/providing an invalid link may result in the issue being closed.**
          placeholder: 'https://github.com/user/my-minimal-snapwp-reproduction'
      validations:
          required: true

    - type: textarea
      attributes:
          label: To Reproduce
          description: A step-by-step description of how to reproduce the issue, based on the linked reproduction.
          placeholder: |
              1. Start the application in development (next dev)
              2. Click X
              3. Y will happen
      validations:
          required: true

    - type: textarea
      attributes:
          label: Additional context
          description: >-
              Add any other context about the problem here that might help us investigate, such as screenshots, error
              logs, etc.

    - type: textarea
      attributes:
          label: Frontend Environment
          description: Please provide details about your frontend environment. We recommend you run `next info` and share the output.
          render: bash

    - type: textarea
      attributes:
          label: Backend Environment
          description: Please provide details about your backend environment. Pleas go to your WordPress `Dashboard > Tools > Site Health > Info`, click `Copy site info to clipboard`, and paste the output here.
          render: markdown
          value: |
              <details>
                <summary>Site Health Info</summary>
                <!-- Please leave one blank line below for enabling the code block rendering. -->

                ```
                PASTE SITE HEALTH INFO HERE
                ```
              </details>

    - type: checkboxes
      attributes:
          label: Please confirm that you have searched existing issues in the repo.
          description: >-
              You can do this by searching
              https://github.com/rtCamp/snapwp/issues and making sure the
              bug has not been reported before.
          options:
              - label: 'Yes'
                required: true
