# Ref - https://verdaccio.org/docs/configuration/

storage: ../storage
auth:
    htpasswd:
        file: ./htpasswd
        max_users: 1
uplinks:
    npmjs:
        url: https://registry.npmjs.org/
packages:
    '@snapwp/*':
        access: $all
        publish: $all
    'snapwp':
        access: $all
        publish: $all
    '**':
        access: $all
        publish: $all
        proxy: npmjs

logs:
    - { type: stdout, format: pretty, level: http }