name: Publish to NPM

on:
    workflow_call:
        inputs:
            updated:
                description: 'JSON Array of updated packages'
                required: true
                type: string

env:
    GRAPHQL_SCHEMA_FILE: '${{ github.workspace }}/schema.graphql'

jobs:
    generate_schema:
        name: Generate WPGraphQL schema
        uses: './.github/workflows/generate-schema.yml'
        with:
            ref: 'main'
        secrets: inherit

    publish:
        runs-on: ubuntu-latest
        needs: generate_schema

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version-file: '.nvmrc'

            - name: Get generated schema
              uses: actions/download-artifact@v4
              with:
                  name: schema
                  path: /tmp/schema

            - name: Move schema to workspace
              run: |
                  cp /tmp/schema/schema.graphql ${{ github.workspace }}/schema.graphql

            - name: Install dependencies
              run: npm ci

            - name: Build
              run: npm run build

            - name: Authenticate with npm
              run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc

            - name: Publish all packages in NPM Workspace to NPM
              run: |
                  sudo apt install jq
                  declare -a package_array=($(echo '${{ inputs.updated }}' | jq -r '.[]'))
                  for package in "${package_array[@]}"; do
                    echo "Publishing $package"
                    location="$(npm query ".workspace#$package" | jq -r '.[0].location')"
                    version="$(npm query ".workspace#$package" | jq -r '.[0].version')"
                    npm publish --access public --workspace "$location" "$package"
                    # Make a GitHub Release
                    bash '${{ github.workspace }}/.github/scripts/release_content.sh' "${{ github.workspace }}/$location/CHANGELOG.md" "$version"
                    gh release create "$package@$version" --title "$package@$version" --notes-file /tmp/changelog.md
                  done
              
                  git push origin develop:main
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
                  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
